### ISSUE TITLE
Does `qw_get_meta_keys` need to be called on the frontend?

### ISSUE THREAD

**Issue by jpSimkins** [daggerhart/query-wrangler#23]
Hello,

I have a question:

Does `qw_get_meta_keys` need to be called on the frontend? I am asking because this query is taking  ~2 seconds to load (due to  filter `qw_fields`). I had to add caching to it since it's so slow. I'll provide that here too (sorry, no PR for this). I am thinking of increasing the cache lifetime to 24 hours since this doesn't change unless I am importing new content.

I currently have 1,864,773 records in the `postmeta` table. This query is single-handedly causing my site to load ~2 seconds longer.

I also don't see why this is being loaded on the frontend. Perhaps this is due to using views? I am not using views and only use the query building part, as the heart of another system I built. 

I'm just trying to figure out if this is actually necessary to be loaded on the frontend or is this only needed on the backend. 

For now, I have wrapped the filter `qw_fields` in a `is_admin()` check in both `meta_value.php` and `meta_value_new.php` (seems like this is for the backend, not the fronend). I don't have any issues... yet.

From a performance perspective, fetching the meta keys on every page load is not ideal at all. The table can get extremely bloated with data so I wouldn't recommend doing this on the frontend. The backend makes sense as it's necessary but definitely not on the frontend.

Thanks!

---

Cache for `qw_get_meta_keys`:
```php
function qw_get_meta_keys() {
	global $wpdb;
	$keys = get_transient('qw_meta_keys');
	if (false === $keys) {
		$keys = $wpdb->get_col("
			SELECT meta_key
			FROM $wpdb->postmeta
			GROUP BY meta_key
			ORDER BY meta_key");
		set_transient('qw_meta_keys', $keys, 900);
	}
	return $keys;
}
```

**Comment by daggerhart** [comment]
I created a new setting that allows you to control the cache life of meta keys.
